services:
  - type: web
    name: light-in-silence-flask
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r NPO-SCA/requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /health-check
    autoDeploy: true
    preDeployCommand: python -m scripts.predeploy
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: FLASK_ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
